---
# tasks file for ec2_provisioning

  - name: Start an instance with a public IP address
    amazon.aws.ec2_instance:
      state: started
      name: "wordpress server"
      key_name: test_keys
      vpc_subnet_id: subnet-07d6ee10c9a12b845
      instance_type: t2.micro
      region: eu-central-1
      security_group: launch-wizard-8
      network:
        assign_public_ip: true
      image_id: ami-0d527b8c289b4af7f
    register: ec2

  - name: Add host to group main_server
    add_host:
      name: '{{ ec2.instances[0].public_ip_address }}'
      groups: main_server

  - name: Wait for SSH to come up
    wait_for: 
      host: '{{ ec2.instances[0].public_ip_address }}'
      port: 22 
      state: started