- name: Provisioning EC2
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - ec2_provisioning



- name: Install WordPress on LEMP stack
  hosts: all
  become: yes

  roles:
    - nginx_configuration
    - mysql_configuration
    - deploy_wp_on_lemp