---
# tasks file for deploy_wp_on_lemp
- name: Update apt-get repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes

- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp



- import_tasks: install_php.yml

- import_tasks: deploy_wodpress.yml


    

  # UFW Configuration


- name: Restart Nginx
  service:
    name: nginx
    state: restarted